### ISSUE TITLE
Error: Unclosed character literal

### ISSUE THREAD

**Issue by alanschlindvein** [michael79bxl/zbtprinter#2]
I'm getting theses errors on the project builder command.

...\platforms\android\src\android\com\github\michael79bxl\zbtprinter\ZebraBluetoothPrinter.java:91: error: unclosed character literal

...\platforms\android\src\android\com\github\michael79bxl\zbtprinter\ZebraBluetoothPrinter.java:91: error: ')' expected thePrinterConn.write(msg.getBytes('UTF-8'));

...\platforms\android\src\android\com\github\michael79bxl\zbtprinter\ZebraBluetoothPrinter.java:91: error: not a statement thePrinterConn.write(msg.getBytes('UTF-8'));

This can be fixed just changing thePrinterConn.write(msg.getBytes('UTF-8')); to thePrinterConn.write(msg.getBytes("UTF-8"));

**Comment by michael79bxl** [comment]
To fix

**Comment by michael79bxl** [comment]
This is not the original source code. If you're using a fork, open the issue in this fork.

`thePrinterConn.write(msg.getBytes());`

**Comment by alanschlindvein** [comment]
Yeah, I saw that when after I opened this issue =P Thanks
