### ISSUE TITLE
Discovery

### ISSUE THREAD

**Issue by bitsprint** [michael79bxl/zbtprinter#3]
Hi,

I can't seem to get printer discovery working.

This works:
```
                    cordova.plugins.zbtprinter.print("AC:3F:A4:1F:6D:1A", label,
                        function (success) {
                            navigator.notification.alert("Print " + success);
                        }, function (fail) {
                            navigator.notification.alert(fail);
                        });

```
This does not work:

```
                     cordova.plugins.zbtprinter.find(
                        function (mac) {
                            navigator.notification.alert(mac);
                        }, function(fail) { 
                            navigator.notification.alert(fail);
                        });
                    

```

I added bluetooth permissions to the AndroidManifest.xml but still no luck. The callback methods are never fired. I also modified the discoveryFinished method in the java to call the error callback but that never fired either. 

Is the project using the latest sdk?

Maybe something stupid I've forgotten? Any help would be gratefully received.

Thanks,

Paul

**Comment by michael79bxl** [comment]
Here are the permissions for one of my apps using this plugin:

```
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>

```
NB: this project was meant to be used with PhoneGap Build.

**Comment by michael79bxl** [comment]
Plugin permissions updated
